name: Update Dataset

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.x

      - name: Install packages
        run: |
          R -e 'install.packages(c("readxl", "tidyverse"))'

      - name: Update dataset
        run: |
          Rscript update_dataset.R

      - name: Commit and push changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"
          git add dataset.csv
          git commit -m "Update dataset"
          git push
